server:
  port: 8383

spring:
  config:
    import: "optional:configserver:"
  application:
      name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: NotificationBack
            uri: lb://NotificationBack
            predicates:
                - Path=/notifications/**
            filters:
              - AddRequestHeader=x-request-from,gateway
              - AddResponseHeader=x-request-from,NotificationBack
          - id: ClientesBack
            uri: lb://ClientesBack
            predicates:
                - Path=/clients/**
            filters:
              - AddRequestHeader=x-request-from,gateway
              - AddResponseHeader=x-request-from,ClientesBack
          - id: BookingBack
            uri: lb://BookingBack
            predicates:
              - Path=/packages/**
            filters:
              - AddRequestHeader=x-request-from,gateway
              - AddResponseHeader=x-request-from,BookingBack
          - id: BookingBack
            uri: lb://BookingBack
            predicates:
              - Path=/hotels/**
            filters:
              - AddRequestHeader=x-request-from,gateway
              - AddResponseHeader=x-request-from,BookingBack
          - id: BookingBack
            uri: lb://BookingBack
            predicates:
              - Path=/activities/**
            filters:
              - AddRequestHeader=x-request-from,gateway
              - AddResponseHeader=x-request-from,BookingBack
          - id: BookingBack
            uri: lb://BookingBack
            predicates:
              - Path=/bookings/**
            filters:
              - AddRequestHeader=x-request-from,gateway
              - AddResponseHeader=x-request-from,BookingBack
          - id: BookingBack
            uri: lb://BookingBack
            predicates:
              - Path=/flights/**
            filters:
              - AddRequestHeader=x-request-from,gateway
              - AddResponseHeader=x-request-from,BookingBack












